uploads = []
generated = []

[[outputs]]
id = "UuD8tuyOWrTYn86OmMjCU"
uri = "file://db/full_dump.zip"
type = "unspecified"
title = "Respaldo actualizado (formato INSERT, compatible con el SQL Editor de Neon)"
