"""Configuración view for ECOMAJES ERP (GERENCIA > Configuración).

Sections:
1. Datos de la Empresa   — nombre, RUC, dirección, teléfono, correo, sedes.
2. Usuarios              — view and manage employees/system users.
3. Roles y Permisos      — read-only display of role definitions.
4. Caja Chica            — register and review petty-cash balance checks.
5. Parámetros            — horarios laborales, límites de stock, otros.
6. Copias de Seguridad   — list of product_backups generated by importers.

Rules enforced:
- No se exponen contraseñas en texto visible.
- Área Administrativa no puede cambiar permisos gerenciales.
- Caja Chica no se considera ingreso; se muestra por separado.
- Toda modificación queda en audit_log con usuario y fecha.
"""

from datetime import date
from decimal import Decimal

import streamlit as st

from ecomajes import config, db


def _money(v) -> float:
    return float(v) if v is not None else 0.0


# --------------------------------------------------------------------------- #
# 1. Datos de la Empresa
# --------------------------------------------------------------------------- #
def _empresa_section(ctx: dict) -> None:
    st.subheader("🏢 Datos de la Empresa")
    current = db.get_empresa_config()

    with st.form("empresa_config_form"):
        col1, col2 = st.columns(2)
        with col1:
            nombre = st.text_input("Nombre de la empresa", value=current.get("nombre", ""))
            ruc = st.text_input("RUC", value=current.get("ruc", ""))
            direccion = st.text_input("Dirección", value=current.get("direccion", ""))
        with col2:
            telefono = st.text_input("Teléfono", value=current.get("telefono", ""))
            correo = st.text_input("Correo electrónico", value=current.get("correo", ""))

        st.markdown("**Nombres de sedes**")
        col3, col4 = st.columns(2)
        with col3:
            sede_principal = st.text_input(
                "Sede Principal", value=current.get("sede_principal", "Sede Principal")
            )
        with col4:
            sede_sucursal = st.text_input(
                "Sucursal", value=current.get("sede_sucursal", "Sucursal")
            )

        submitted = st.form_submit_button("💾 Guardar datos de empresa")

    if submitted:
        if not nombre.strip():
            st.error("El nombre de la empresa es obligatorio.")
            return
        try:
            db.save_empresa_config(
                {
                    "nombre": nombre.strip(),
                    "ruc": ruc.strip(),
                    "direccion": direccion.strip(),
                    "telefono": telefono.strip(),
                    "correo": correo.strip(),
                    "sede_principal": sede_principal.strip() or "Sede Principal",
                    "sede_sucursal": sede_sucursal.strip() or "Sucursal",
                },
                usuario_rol=ctx["usuario_rol"],
            )
            db.log_audit(
                db.AUDIT_CONFIG,
                "Configuración",
                detalle="Datos de empresa actualizados",
                usuario_rol=ctx["usuario_rol"],
            )
        except Exception as exc:  # noqa: BLE001
            st.error(f"No se pudo guardar: {exc}")
        else:
            st.success("Datos de empresa guardados correctamente.")
            st.rerun()


# --------------------------------------------------------------------------- #
# 2. Usuarios
# --------------------------------------------------------------------------- #
def _usuarios_section(ctx: dict) -> None:
    st.subheader("👤 Usuarios")

    col_search, col_sede = st.columns(2)
    with col_search:
        search = st.text_input("🔍 Buscar usuario", key="cfg_user_search")
    with col_sede:
        sede_opts = ["Todas"] + config.get_sedes(config.ROLE_GERENCIA)[:2]
        sede_filter = st.selectbox("Sede", sede_opts, key="cfg_user_sede")

    employees = db.list_employees(
        search=search.strip() or None,
        sede=None if sede_filter == "Todas" else sede_filter,
    )

    rows = [
        {
            "Nombre": e["nombre"],
            "Usuario": e["username"],
            "Documento": e.get("documento") or "—",
            "Cargo": e.get("cargo") or "—",
            "Rol": e["rol"],
            "Sede": e.get("sede") or "—",
            "Estado": db.EMPLOYEE_STATUS_LABELS.get(e["estado"], e["estado"]),
            "Fecha ingreso": (
                e["fecha_ingreso"].strftime("%Y-%m-%d") if e["fecha_ingreso"] else "—"
            ),
        }
        for e in employees
    ]
    if rows:
        st.dataframe(rows, use_container_width=True, hide_index=True)
        st.caption(f"{len(rows)} usuario(s) encontrado(s).")
    else:
        st.info("No hay usuarios registrados.")

    if ctx["editable"]:
        with st.expander("➕ Crear nuevo usuario"):
            with st.form("cfg_create_user", clear_on_submit=True):
                c1, c2 = st.columns(2)
                with c1:
                    u_nombre = st.text_input("Nombre completo")
                    u_username = st.text_input("Nombre de usuario")
                    u_password = st.text_input("Contraseña", type="password")
                    u_rol = st.selectbox("Rol", config.ROLES)
                with c2:
                    u_documento = st.text_input("Documento de identidad")
                    u_cargo = st.text_input("Cargo")
                    u_sede = st.selectbox(
                        "Sede", config.get_sedes(config.ROLE_GERENCIA)[:2]
                    )
                    u_salario = st.number_input("Salario", min_value=0.0, step=50.0)
                u_submitted = st.form_submit_button("Crear usuario")

            if u_submitted:
                if not u_nombre.strip() or not u_username.strip() or not u_password:
                    st.error("Nombre, usuario y contraseña son obligatorios.")
                else:
                    try:
                        db.create_employee(
                            nombre=u_nombre.strip(),
                            username=u_username.strip(),
                            password=u_password,
                            rol=u_rol,
                            documento=u_documento.strip() or None,
                            cargo=u_cargo.strip() or None,
                            sede=u_sede,
                            salario=Decimal(str(u_salario)),
                        )
                        db.log_audit(
                            db.AUDIT_CONFIG,
                            "Configuración",
                            detalle=f"Usuario creado: {u_username.strip()}",
                            usuario_rol=ctx["usuario_rol"],
                        )
                    except db.EmployeeError as exc:
                        st.error(str(exc))
                    except Exception as exc:  # noqa: BLE001
                        st.error(f"Error: {exc}")
                    else:
                        st.success(f"Usuario «{u_nombre.strip()}» creado.")
                        st.rerun()

        if employees:
            with st.expander("✏️ Editar / Activar / Desactivar usuario"):
                by_id = {e["id"]: e for e in employees}
                sel_id = st.selectbox(
                    "Seleccionar usuario",
                    list(by_id.keys()),
                    format_func=lambda i: f"{by_id[i]['nombre']} ({by_id[i]['username']})",
                    key="cfg_edit_user_select",
                )
                emp = by_id[sel_id]
                with st.form(f"cfg_edit_user_{sel_id}"):
                    c1, c2 = st.columns(2)
                    with c1:
                        e_nombre = st.text_input("Nombre", value=emp["nombre"])
                        e_username = st.text_input("Usuario", value=emp["username"])
                        e_password = st.text_input(
                            "Nueva contraseña (vacío = sin cambio)", type="password"
                        )
                        current_rol = (
                            emp["rol"] if emp["rol"] in config.ROLES else config.ROLES[0]
                        )
                        e_rol = st.selectbox(
                            "Rol", config.ROLES, index=config.ROLES.index(current_rol)
                        )
                    with c2:
                        e_doc = st.text_input("Documento", value=emp.get("documento") or "")
                        e_cargo = st.text_input("Cargo", value=emp.get("cargo") or "")
                        sede_opts2 = config.get_sedes(config.ROLE_GERENCIA)[:2]
                        e_sede = st.selectbox(
                            "Sede",
                            sede_opts2,
                            index=sede_opts2.index(emp["sede"])
                            if emp.get("sede") in sede_opts2
                            else 0,
                        )
                        e_salario = st.number_input(
                            "Salario",
                            min_value=0.0,
                            value=float(emp["salario"] or 0),
                            step=50.0,
                        )
                    e_estado = st.selectbox(
                        "Estado",
                        list(db.EMPLOYEE_STATUS_LABELS.keys()),
                        index=list(db.EMPLOYEE_STATUS_LABELS.keys()).index(emp["estado"])
                        if emp["estado"] in db.EMPLOYEE_STATUS_LABELS
                        else 0,
                        format_func=lambda k: db.EMPLOYEE_STATUS_LABELS[k],
                    )
                    e_submitted = st.form_submit_button("Guardar cambios")

                if e_submitted:
                    if not e_nombre.strip() or not e_username.strip():
                        st.error("Nombre y usuario son obligatorios.")
                    else:
                        try:
                            db.update_employee(
                                employee_id=sel_id,
                                nombre=e_nombre.strip(),
                                username=e_username.strip(),
                                rol=e_rol,
                                estado=e_estado,
                                telefono=emp.get("telefono"),
                                direccion=emp.get("direccion"),
                                fecha_ingreso=emp.get("fecha_ingreso"),
                                salario=Decimal(str(e_salario)),
                                password=e_password or None,
                                documento=e_doc.strip() or None,
                                cargo=e_cargo.strip() or None,
                                sede=e_sede,
                            )
                            db.log_audit(
                                db.AUDIT_CONFIG,
                                "Configuración",
                                detalle=f"Usuario editado: {e_username.strip()}",
                                usuario_rol=ctx["usuario_rol"],
                            )
                        except db.EmployeeError as exc:
                            st.error(str(exc))
                        except Exception as exc:  # noqa: BLE001
                            st.error(f"Error: {exc}")
                        else:
                            st.success("Usuario actualizado.")
                            st.rerun()


# --------------------------------------------------------------------------- #
# 3. Roles y Permisos
# --------------------------------------------------------------------------- #
def _roles_section() -> None:
    st.subheader("🔐 Roles y Permisos")
    st.caption("Los roles y permisos están definidos en el sistema. Solo GERENCIA puede gestionarlos.")

    data = [
        {
            "Rol": config.ROLE_OPERARIOS,
            "Acceso": "Control de Asistencia, Inventario (lectura), Comentarios",
            "Requiere contraseña": "No",
        },
        {
            "Rol": config.ROLE_ADMINISTRATIVA,
            "Acceso": "Material Nuevo, Material Segundo Uso, Importar, Comentarios",
            "Requiere contraseña": "Sí",
        },
        {
            "Rol": config.ROLE_GERENCIA,
            "Acceso": "Acceso completo: Panel, Ventas, Productos, Precios, RR.HH., Balance, Configuración, Auditoría",
            "Requiere contraseña": "Sí",
        },
    ]
    st.dataframe(data, use_container_width=True, hide_index=True)
    st.info(
        "ℹ️ Área Administrativa no puede cambiar permisos gerenciales. "
        "Para modificar roles, contacte al administrador del sistema."
    )


# --------------------------------------------------------------------------- #
# 4. Caja Chica
# --------------------------------------------------------------------------- #
def _caja_chica_section(ctx: dict) -> None:
    st.subheader("💼 Caja Chica")
    st.caption(
        "La Caja Chica es un fondo fijo. **No se considera ingreso** y se muestra "
        "por separado en el Balance Financiero."
    )

    sede_opts = [config.SEDE_PRINCIPAL, config.SEDE_SUCURSAL]
    sede_sel = st.selectbox("Sede", sede_opts, key="cfg_cc_sede")

    if ctx["editable"]:
        with st.expander("➕ Registrar revisión de Caja Chica"):
            with st.form("cfg_caja_chica_form", clear_on_submit=True):
                c1, c2 = st.columns(2)
                with c1:
                    cc_fecha = st.date_input("Fecha", value=date.today(), key="cfg_cc_fecha")
                    cc_base = st.number_input(
                        "Monto base (fondo fijo)", min_value=0.0, step=10.0, key="cfg_cc_base"
                    )
                with c2:
                    cc_contado = st.number_input(
                        "Dinero contado", min_value=0.0, step=10.0, key="cfg_cc_contado"
                    )
                    cc_diferencia = cc_contado - cc_base
                    st.metric("Diferencia", f"$ {cc_diferencia:,.2f}")
                cc_obs = st.text_area("Observación", key="cfg_cc_obs")
                cc_sub = st.form_submit_button("Guardar registro")

            if cc_sub:
                try:
                    db.save_caja_chica(
                        fecha=cc_fecha,
                        sede=sede_sel,
                        monto_base=Decimal(str(cc_base)),
                        dinero_contado=Decimal(str(cc_contado)),
                        observaciones=cc_obs.strip() or None,
                        usuario_rol=ctx["usuario_rol"],
                    )
                    db.log_audit(
                        db.AUDIT_CONFIG,
                        "Configuración",
                        detalle=f"Caja Chica registrada · {sede_sel} · diferencia ${cc_diferencia:,.2f}",
                        usuario_rol=ctx["usuario_rol"],
                        sede=sede_sel,
                    )
                except Exception as exc:  # noqa: BLE001
                    st.error(f"No se pudo guardar: {exc}")
                else:
                    st.success("Registro de Caja Chica guardado.")
                    st.rerun()

    # History
    today = date.today()
    month_start = today.replace(day=1)
    c1, c2 = st.columns(2)
    with c1:
        cc_from = st.date_input("Desde", value=month_start, key="cfg_cc_from")
    with c2:
        cc_to = st.date_input("Hasta", value=today, key="cfg_cc_to")

    registros = db.list_caja_chica(sede=sede_sel, date_from=cc_from, date_to=cc_to)
    if not registros:
        st.info("No hay registros de Caja Chica para el filtro seleccionado.")
        return

    rows = [
        {
            "Fecha": r["fecha"].strftime("%Y-%m-%d"),
            "Sede": r["sede"],
            "Monto base": _money(r["monto_base"]),
            "Contado": _money(r["dinero_contado"]),
            "Diferencia": _money(r["diferencia"]),
            "Observación": r["observaciones"] or "—",
            "Registrado por": r["usuario_rol"] or "—",
        }
        for r in registros
    ]
    st.dataframe(rows, use_container_width=True, hide_index=True)


# --------------------------------------------------------------------------- #
# 5. Parámetros del sistema
# --------------------------------------------------------------------------- #
_PARAMS_CATALOG = [
    ("horario_entrada", "Hora de entrada (HH:MM)", "08:00"),
    ("horario_salida", "Hora de salida (HH:MM)", "18:00"),
    ("tolerancia_tardanza_min", "Tolerancia de tardanza (minutos)", "15"),
    ("stock_minimo_global", "Stock mínimo global (unidades)", "5"),
    ("moneda", "Moneda", "S/."),
    ("dias_laborales", "Días laborales (ej: Lun-Sab)", "Lunes-Sábado"),
]


def _parametros_section(ctx: dict) -> None:
    st.subheader("⚙️ Parámetros del Sistema")
    st.caption("Parámetros autorizados que controlan el comportamiento del sistema.")

    # Fetch current values
    params_stored = {p["clave"]: p for p in db.list_system_params()}

    with st.form("cfg_params_form"):
        values: dict[str, str] = {}
        for clave, label, default in _PARAMS_CATALOG:
            stored = params_stored.get(clave)
            current_val = stored["valor"] if stored and stored["valor"] is not None else default
            values[clave] = st.text_input(label, value=current_val, key=f"param_{clave}")

        p_submitted = st.form_submit_button("💾 Guardar parámetros")

    if p_submitted:
        try:
            for clave, label, _ in _PARAMS_CATALOG:
                valor = values[clave].strip()
                db.set_system_param(
                    clave=clave,
                    valor=valor,
                    descripcion=label,
                    usuario_rol=ctx["usuario_rol"],
                )
            db.log_audit(
                db.AUDIT_CONFIG,
                "Configuración",
                detalle="Parámetros del sistema actualizados",
                usuario_rol=ctx["usuario_rol"],
            )
        except Exception as exc:  # noqa: BLE001
            st.error(f"No se pudo guardar: {exc}")
        else:
            st.success("Parámetros guardados.")
            st.rerun()


# --------------------------------------------------------------------------- #
# 6. Copias de seguridad
# --------------------------------------------------------------------------- #
def _backups_section() -> None:
    st.subheader("🗄️ Copias de Seguridad")
    st.caption(
        "Las copias de seguridad se generan automáticamente antes de cada importación de productos. "
        "**No se borran datos ni se exponen credenciales.**"
    )

    import psycopg2.extras as _extras

    with db._get_conn() as conn:
        with conn.cursor(cursor_factory=_extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT id, created_at, import_mode, product_count, restored_at "
                "FROM product_backups ORDER BY created_at DESC LIMIT 50"
            )
            backups = [dict(r) for r in cur.fetchall()]

    if not backups:
        st.info("No hay copias de seguridad registradas todavía.")
        return

    rows = [
        {
            "ID": b["id"],
            "Fecha": b["created_at"].strftime("%Y-%m-%d %H:%M"),
            "Modo": b["import_mode"],
            "Productos": b["product_count"],
            "Restaurado en": b["restored_at"].strftime("%Y-%m-%d %H:%M")
            if b["restored_at"]
            else "—",
        }
        for b in backups
    ]
    st.dataframe(rows, use_container_width=True, hide_index=True)
    st.caption(
        "Para restaurar una copia, use la opción de restauración en el módulo de importación."
    )


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #
def render(ctx: dict) -> None:
    st.header(ctx["title"])
    st.caption(ctx["breadcrumb"])

    tabs = st.tabs([
        "🏢 Empresa",
        "👤 Usuarios",
        "🔐 Roles y Permisos",
        "💼 Caja Chica",
        "⚙️ Parámetros",
        "🗄️ Copias de Seguridad",
    ])

    with tabs[0]:
        _empresa_section(ctx)

    with tabs[1]:
        _usuarios_section(ctx)

    with tabs[2]:
        _roles_section()

    with tabs[3]:
        _caja_chica_section(ctx)

    with tabs[4]:
        _parametros_section(ctx)

    with tabs[5]:
        _backups_section()
